/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;

import Observer.*;
import Decorators.*;
import Bebidas.*;
import Combos.Combo;
import Decorators.Sustituto;
import Modelos.Mensaje;
import Productos.*;
import Productos.ProductoFactory;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @Daniel 
 */
public class PantallaCliente extends javax.swing.JFrame implements Observer {
    Cliente cliente;
    DefaultListModel<String> modeloLista;
    Producto[] productos;
    int[] cantidades;
    Observable observable;
    int indice;

    public PantallaCliente() {
        setTitle("Carrito");
        setResizable(false);
        initComponents();
        cliente = new Cliente(this);
        modeloLista = new DefaultListModel<>();
        listCarrito.setModel(modeloLista);
        productos = new Producto[50];
        cantidades = new int[50];
        indice = 0;
        llenarComboProductos();
        actualizarEstadoBotonHacerPedido();
        setLocationRelativeTo(null);

        observable = new Observable();
        observable.addObserver((Observer) this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboProductos = new javax.swing.JComboBox<>();
        btnAgregarProducto = new javax.swing.JButton();
        comboCombos = new javax.swing.JComboBox<>();
        btnAgregarCombo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCarrito = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        btnHacerPedido = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        rdbtnAgrandar = new javax.swing.JRadioButton();
        rdbtnAzucar = new javax.swing.JRadioButton();
        rdbtnChispas = new javax.swing.JRadioButton();
        rdbtnCrema = new javax.swing.JRadioButton();
        rdbtnDiseño = new javax.swing.JRadioButton();
        rdbtnHielo = new javax.swing.JRadioButton();
        rdbtnLeche = new javax.swing.JRadioButton();
        rdbtnDulce = new javax.swing.JRadioButton();
        rdbtnMalvaviscos = new javax.swing.JRadioButton();
        rdbtnSustituto = new javax.swing.JRadioButton();
        btnDecorar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Café" }));
        comboProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductosActionPerformed(evt);
            }
        });

        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        comboCombos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Combo 1" }));
        comboCombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCombosActionPerformed(evt);
            }
        });

        btnAgregarCombo.setText("Agreagar Combo");
        btnAgregarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarComboActionPerformed(evt);
            }
        });

        listCarrito.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listCarrito);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Carrito");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agregar Compra");

        labelTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelTotal.setText("Total = $0");

        btnHacerPedido.setBackground(new java.awt.Color(153, 255, 153));
        btnHacerPedido.setText("Hacer Pedido");
        btnHacerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHacerPedidoActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setText("Eliminar Producto");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHacerPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTotal)
                                .addGap(150, 150, 150))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarCombo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarProducto))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel2)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProducto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCombos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCombo))
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(labelTotal)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHacerPedido)
                    .addComponent(btnEliminar))
                .addGap(30, 30, 30))
        );

        rdbtnAgrandar.setText("Agrandar");
        rdbtnAgrandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnAgrandarActionPerformed(evt);
            }
        });

        rdbtnAzucar.setText("Azúcar");
        rdbtnAzucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnAzucarActionPerformed(evt);
            }
        });

        rdbtnChispas.setText("Chispas");
        rdbtnChispas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnChispasActionPerformed(evt);
            }
        });

        rdbtnCrema.setText("Crema");
        rdbtnCrema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnCremaActionPerformed(evt);
            }
        });

        rdbtnDiseño.setText("Diseño");
        rdbtnDiseño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnDiseñoActionPerformed(evt);
            }
        });

        rdbtnHielo.setText("Hielo");
        rdbtnHielo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnHieloActionPerformed(evt);
            }
        });

        rdbtnLeche.setText("Leche");
        rdbtnLeche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnLecheActionPerformed(evt);
            }
        });

        rdbtnDulce.setText("Dulce");
        rdbtnDulce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnDulceActionPerformed(evt);
            }
        });

        rdbtnMalvaviscos.setText("Malvaviscos");
        rdbtnMalvaviscos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnMalvaviscosActionPerformed(evt);
            }
        });

        rdbtnSustituto.setText("Sustituto");
        rdbtnSustituto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnSustitutoActionPerformed(evt);
            }
        });

        btnDecorar.setText("Decorar");
        btnDecorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecorarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnAzucar)
                    .addComponent(rdbtnAgrandar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnCrema)
                    .addComponent(rdbtnChispas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnHielo)
                    .addComponent(rdbtnDiseño))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnDulce)
                    .addComponent(rdbtnLeche))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnSustituto)
                    .addComponent(rdbtnMalvaviscos)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDecorar)
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbtnAgrandar)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtnAzucar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbtnChispas)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtnCrema))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbtnDiseño)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtnHielo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbtnLeche)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtnDulce))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbtnMalvaviscos)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtnSustituto)))
                .addGap(18, 18, 18)
                .addComponent(btnDecorar)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        seleccionarProductoIndividual();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void comboProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductosActionPerformed

    }//GEN-LAST:event_comboProductosActionPerformed

    private void btnHacerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHacerPedidoActionPerformed
        hacerPedido();
    }//GEN-LAST:event_btnHacerPedidoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarProducto();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void comboCombosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCombosActionPerformed

    }//GEN-LAST:event_comboCombosActionPerformed

    private void btnAgregarComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarComboActionPerformed
        seleccionarCombo();
    }//GEN-LAST:event_btnAgregarComboActionPerformed

    private void btnDecorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecorarActionPerformed
        decorarBebida();
    }//GEN-LAST:event_btnDecorarActionPerformed

    private void rdbtnAgrandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnAgrandarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnAgrandarActionPerformed

    private void rdbtnAzucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnAzucarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnAzucarActionPerformed

    private void rdbtnChispasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnChispasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnChispasActionPerformed

    private void rdbtnCremaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnCremaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnCremaActionPerformed

    private void rdbtnDiseñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnDiseñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnDiseñoActionPerformed

    private void rdbtnHieloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnHieloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnHieloActionPerformed

    private void rdbtnLecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnLecheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnLecheActionPerformed

    private void rdbtnDulceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnDulceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnDulceActionPerformed

    private void rdbtnMalvaviscosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnMalvaviscosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnMalvaviscosActionPerformed

    private void rdbtnSustitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnSustitutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnSustitutoActionPerformed
    
    
    private void llenarComboProductos() {
        Producto[] todosLosProductos = {new Cafe(), new Te(), new Chocolate(), new Capuccino(), new Frappe(), new Gaseosa(), new Natural(), 
            new Matcha(), new Smoothie(), new Espresso(), new Burrito(), new Casado(), new Hamburguesa(), new Papas(), new Pinto(), new Pizza(), 
            new Pupusa(), new Reposteria(), new Sandwich(), new Sopa(), new Tacos()};

        comboProductos.removeAllItems();
        for (Producto producto : todosLosProductos) {
            comboProductos.addItem(producto.getDescripcion() + " - $" + producto.getCosto());
        }

        comboCombos.removeAllItems();
        comboCombos.addItem("Combo Desayuno - $" + ProductoFactory.obtenerCostoCombo("Combo Desayuno"));
        comboCombos.addItem("Combo Almuerzo - $" + ProductoFactory.obtenerCostoCombo("Combo Almuerzo"));
        comboCombos.addItem("Combo Café - $" + ProductoFactory.obtenerCostoCombo("Combo Café"));
        comboCombos.addItem("Combo Cena - $" + ProductoFactory.obtenerCostoCombo("Combo Cena"));
        comboCombos.addItem("Combo Smoothie - $" + ProductoFactory.obtenerCostoCombo("Combo Smoothie"));
        comboCombos.addItem("Combo Pizza - $" + ProductoFactory.obtenerCostoCombo("Combo Pizza"));
        comboCombos.addItem("Combo Sandwich - $" + ProductoFactory.obtenerCostoCombo("Combo Sandwich"));
        comboCombos.addItem("Combo Hamburguesa - $" + ProductoFactory.obtenerCostoCombo("Combo Hamburguesa"));
        comboCombos.addItem("Combo Tacos - $" + ProductoFactory.obtenerCostoCombo("Combo Tacos"));
        comboCombos.addItem("Combo Burrito - $" + ProductoFactory.obtenerCostoCombo("Combo Burrito"));
    }

    private void seleccionarProductoIndividual() {
        String productoSeleccionado = (String) comboProductos.getSelectedItem();
        if (productoSeleccionado != null) {
            String[] parts = productoSeleccionado.split(" - \\$");
            String nombreProducto = parts[0];

            Producto producto = ProductoFactory.crearProducto(nombreProducto); // Método hipotético para crear producto
            if (producto != null) {
                int pos = encontrarPosicionProducto(producto);
                if (pos != -1) {
                    cantidades[pos]++;
                } else {
                    productos[indice] = producto;
                    cantidades[indice] = 1;
                    indice++;
                }
                actualizarCarrito();
                observable.notifyObservers();
            }
        }
    }

    private void seleccionarCombo() {
    String comboSeleccionado = (String) comboCombos.getSelectedItem();
    if (comboSeleccionado != null) {
        String[] parts = comboSeleccionado.split(" - \\$");
        String nombreCombo = parts[0];

        Combo combo = ProductoFactory.crearCombo(nombreCombo);
        if (combo != null) {
            int pos = encontrarPosicionProducto(combo);
            if (pos != -1) {
                cantidades[pos]++;
            } else {
                productos[indice] = combo;
                cantidades[indice] = 1;
                indice++;
            }
            actualizarCarrito();
            observable.notifyObservers();
        }
    }
    }

    private void hacerPedido() {
    String[] productosPedido = new String[indice];
    for (int i = 0; i < indice; i++) {
        double costo = productos[i] instanceof Combo ? productos[i].getCosto() * 0.90 : productos[i].getCosto();
        productosPedido[i] = cantidades[i] + " x " + productos[i].getDescripcion() + " - $" + String.format("%.2f", costo * cantidades[i]);
    }
    Mensaje mensaje = new Mensaje(productosPedido);
    cliente.enviarPedido(mensaje);
    limpiarCarrito();
    observable.notifyObservers();
}

    private void eliminarProducto() {
    int index = listCarrito.getSelectedIndex();
    if (index != -1) {
        String item = modeloLista.getElementAt(index);
        String[] parts = item.split(" x ");
        int cantidad = Integer.parseInt(parts[0]);
        String nombreProducto = parts[1].split(" - \\$")[0];

        Producto producto = encontrarProducto(nombreProducto);
        if (producto != null) {
            int pos = encontrarPosicionProducto(producto);
            if (pos != -1) {
                cantidades[pos] -= cantidad;
                if (cantidades[pos] <= 0) {
                    for (int i = pos; i < indice - 1; i++) {
                        productos[i] = productos[i + 1];
                        cantidades[i] = cantidades[i + 1];
                    }
                    indice--;
                }
                actualizarCarrito();
                observable.notifyObservers();
            }
        }
    }
    }

    private Producto encontrarProducto(String nombre) {
        for (int i = 0; i < indice; i++) {
            if (productos[i].getDescripcion().equals(nombre)) {
                return productos[i];
            }
        }
        return null;
    }

    private int encontrarPosicionProducto(Producto producto) {
    for (int i = 0; i < indice; i++) {
        if (productos[i].getDescripcion().equals(producto.getDescripcion())) {
            return i;
        }
    }
    return -1;
}

    private void actualizarCarrito() {
    modeloLista.clear();
    for (int i = 0; i < indice; i++) {
        Producto producto = productos[i];
        double costo = producto instanceof Combo ? producto.getCosto() * 0.90 : producto.getCosto();
        modeloLista.addElement(cantidades[i] + " x " + producto.getDescripcion() + " - $" + (costo * cantidades[i]));
    }
    actualizarTotal();
    actualizarEstadoBotonHacerPedido();
    }

    private void limpiarCarrito() {
        for (int i = 0; i < indice; i++) {
            productos[i] = null;
            cantidades[i] = 0;
        }
        indice = 0;
        modeloLista.clear();
    }

    private void actualizarTotal() {
        double total = 0.0;
        for (int i = 0; i < indice; i++) {
            total += productos[i].getCosto() * cantidades[i];
        }
        labelTotal.setText("Total: $" + String.format("%.2f", total));
    }

    private void actualizarEstadoBotonHacerPedido() {
        btnHacerPedido.setEnabled(indice > 0);
    }

    private void decorarBebida() {
    int index = listCarrito.getSelectedIndex();
    if (index != -1) {
        String item = modeloLista.get(index);
        String[] parts = item.split(" x ");
        String nombreProducto = parts[1].split(" - \\$")[0];

        Producto bebida = encontrarProducto(nombreProducto);
        if (bebida != null) {
            Producto bebidaDecorada = bebida;
            String descripcionOriginal = bebida.getDescripcion();

            if (rdbtnAgrandar.isSelected() && !descripcionOriginal.contains("Agrandar")) {
                bebidaDecorada = new Agrandar(bebidaDecorada);
            }
            if (rdbtnAzucar.isSelected() && !descripcionOriginal.contains("Azucar")) {
                bebidaDecorada = new Azucar(bebidaDecorada);
            }
            if (rdbtnChispas.isSelected() && !descripcionOriginal.contains("Chispas")) {
                bebidaDecorada = new Chispas(bebidaDecorada);
            }
            if (rdbtnCrema.isSelected() && !descripcionOriginal.contains("Crema")) {
                bebidaDecorada = new Crema(bebidaDecorada);
            }
            if (rdbtnDiseño.isSelected() && !descripcionOriginal.contains("Diseño")) {
                bebidaDecorada = new Diseño(bebidaDecorada);
            }
            if (rdbtnDulce.isSelected() && !descripcionOriginal.contains("Dulce")) {
                bebidaDecorada = new Dulce(bebidaDecorada);
            }
            if (rdbtnHielo.isSelected() && !descripcionOriginal.contains("Hielo")) {
                bebidaDecorada = new Hielo(bebidaDecorada);
            }
            if (rdbtnLeche.isSelected() && !descripcionOriginal.contains("Leche")) {
                bebidaDecorada = new Leche(bebidaDecorada);
            }
            if (rdbtnMalvaviscos.isSelected() && !descripcionOriginal.contains("Malvaviscos")) {
                bebidaDecorada = new Malvaviscos(bebidaDecorada);
            }
            if (rdbtnSustituto.isSelected() && !descripcionOriginal.contains("Sustituto")) {
                bebidaDecorada = new Sustituto(bebidaDecorada);
            }

            int pos = encontrarPosicionProducto(bebida);
            if (pos != -1) {
                productos[pos] = bebidaDecorada;
                actualizarCarrito();
                observable.notifyObservers();
            }
        } else {
            write("Producto no encontrado para decorar.");
        }
    } else {
        write("Seleccione una bebida en el carrito para decorar.");
    }
}

    public void write(String text) {
        JOptionPane.showMessageDialog(this, text);
    }

    public void update() {
        actualizarTotal();
        actualizarEstadoBotonHacerPedido();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> new PantallaCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCombo;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnDecorar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHacerPedido;
    private javax.swing.JComboBox<String> comboCombos;
    private javax.swing.JComboBox<String> comboProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JList<String> listCarrito;
    private javax.swing.JRadioButton rdbtnAgrandar;
    private javax.swing.JRadioButton rdbtnAzucar;
    private javax.swing.JRadioButton rdbtnChispas;
    private javax.swing.JRadioButton rdbtnCrema;
    private javax.swing.JRadioButton rdbtnDiseño;
    private javax.swing.JRadioButton rdbtnDulce;
    private javax.swing.JRadioButton rdbtnHielo;
    private javax.swing.JRadioButton rdbtnLeche;
    private javax.swing.JRadioButton rdbtnMalvaviscos;
    private javax.swing.JRadioButton rdbtnSustituto;
    // End of variables declaration//GEN-END:variables
}
